name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: python:3.13-slim

    env:
      PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y libgl1 libglx-mesa0 libxkbcommon0 libdbus-1-3 libglib2.0-0 libgdk-pixbuf2.0-0 libx11-6 libxcb1

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --cov-report xml:cov.xml --cov
          coverage report --fail-under=100
